projectLanguage: "ts"
locations:
  base: src
  arguments: arguments
  commands: commands
  listeners: listeners
  preconditions: preconditions
  components: components
customFileTemplates:
  enabled: true
  location: "src/templates"
